import type { Metadata } from "next";
import LayoutContent from "@/components/LayoutContent";
import "@/styles/globals.css";
import { cookies } from "next/headers";
import bcrypt from "bcryptjs";
import jwt from "jsonwebtoken";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let isLogin = false;
  let username = "";
  const SECRET_KEY = process.env.SECRET_KEY || "";
  const cookieStore = cookies();
  const token = cookieStore.get("token")?.value || "";


  if (token) {
    try {
        const decoded = jwt.verify(token, SECRET_KEY) as { username: string };
        isLogin = true;
        username = decoded.username
    } catch (error) {
        console.error("Error verifying token:", error);
        isLogin = false;
        username = "";
    }
}

  return (
    <html lang="en">
      <body className="">
        <LayoutContent isLogin={isLogin} username={username}>{children}</LayoutContent>
      </body>
    </html>
  );
}
